# Generated by Django 2.0.4 on 2018-07-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='up_count',
        ),
    ]
