# Generated by Django 2.0.4 on 2018-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180710_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set(),
        ),
    ]
